name: responsive_framework
description: Make Flutter apps responsive. Automatically adapt UI to different screen sizes.
version: 0.0.3
homepage: https://codelessly.com
repository: https://github.com/Codelessly/ResponsiveFramework
issue_tracker: https://github.com/Codelessly/ResponsiveFramework/issues
documentation: https://github.com/Codelessly/ResponsiveFramework

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: